---
uuid: c2b153dd-3a11-46b5-a24f-baf5c71709f9
description: 
title: 제너레이터와 async/await
tags: [javascript]
date: 2021-01-29T15:00:00.000Z
---







ES6에 도입된 제너레이터는 코드 블록의 실행을 일시중지했다가 필요한 시점에 재개할 수 있는 특수함수이다.

**제너레이터 vs 일반함수**

- 제너레이터 함수는 함수호출자에게 함수 실행의 제어권을 양도가능하다.
    
    → 함수의 제어권을 함수가 독점하지 않고 함수호출자에게 yield 키워드로 양도가 가능하다.
    
- 제너레이터 함수는 함수호출자와 상태를 주고받을 수 있다.
    
    → 제너레이터는 함수호출자에게 상태를 전달하고 함수호출자로부터 상태를 전달받을 수 있다.
    
- 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.
    
    → 제너레이터 함수를 호출하면 코드를 실행하는것이 아니라 이터러블이면서 이터레이터인 제너레이터 객체를 반환한다.
    

### 제너레이터 함수의 정의

```jsx
// 제너레이터 함수 선언문
function* genStatement(){
	yield 1;
}

// 제너레이터 함수 표현식
const genExpression = function* () {
	yield 1;
}

// 제너레이터 메서드
const obj = {
	* genMethod() {
		yield 1;
	}
}
```

애스터리스크의 위치는 function 키워드와 함수 이름 사이라면 어디든지 상관없다.

### 제너레이터 함수의 특징

- 화살표함수로는 정의가 불가능하다.
- new 연산자와 함께 생성자함수로 사용이 불가능하다.

```jsx
// 화살표함수
const genArrowFunc = * () => {
	yield 1;
}
// Uncaught SyntaxError: Unexpected token '*'

// 생성자함수
const genConstructorFunc = function* () {
	yield 1;
}
const genInstance = new genConstructorFunc();
// Uncaught TypeError: genConstructorFunc is not a constructor
```

### 제너레이터 객체

제너레이터 함수를 호출하면 일반 함수처럼 함수 코드블록을 실행하는 것이 아니라 제너레이터 객체를 생성해 반환한다. 제너레이터 함수가 반환한 제너레이터 객체는 이터러블이면서 동시에 이터레이터이다.

```jsx
function* genFunc() {
    yield 1;
    yield 2;
    yield 3;
}
const gen = genFunc();
console.log(Symbol.iterator in gen); // true
console.log('next' in gen); // true
console.log('throw' in gen); // true
console.log('return' in gen); // true
```

단, 제너레이터는 이터레이터에 없는 return, throw 메서드를 갖는다.

**next 메서드**

yield 표현식까지 코드블록을 실행하고 yield 값을 value 프로퍼티로 순회완료여부를 done 프로퍼티로 담은 이터레이터 리절트 객체를 반환한다.

```jsx
console.log(gen.next()); // {value: 1, done: false}
```

**return 메서드**

인수로 전달받은 값을 value 프로퍼티로, true 값을 done 프로퍼티로 담은 이터레이터 리절트 객체를 반환한다.

```jsx
console.log(gen.return('done')); // {value: 'done', done: true}
console.log(gen.next()); // {value: undefined, done: true}
```

**throw 메서드**

인수로 전달받은 에러를 발생시키고 undefined를 value 프로퍼티로, true를 done 프로퍼티로 담은 이터레이터 리절트 객체를 반환한다.

```jsx
function* genFunc() {
    try {
        yield 1;
        yield 2;
        yield 3;
    } catch (e) {
        console.error(e);
    }
}
const gen = genFunc();
console.log(gen.throw('throw')); // throw { value: undefined, done: true }
```

### 제너레이터의 일시 중지와 재개

yield 키워드는 제너레이터 함수의 실행을 일시 중지시키거나 yield 키워드 뒤에 오는 표현식의 평가 결과를 제너레이터 함수 호출자에게 반환한다.

```jsx
function* genFunc() {
    const x = yield 1;
    const y = yield x + 10;
    return x + y;
}

const gen = genFunc();
let res = gen.next();
console.log(res); // { value: 1, done: false }

res = gen.next(10);
console.log(res); // { value: 20, done: false }

res = gen.next(20);
console.log(res); // { value: 30, done: true }
```

### 제너레이터의 활용

**이터러블의 구현**

```jsx
// 이터레이터
const iterFibonacci = function () {
    let [pre, cur] = [0, 1];
    return {
        [Symbol.iterator]() {
            return this;
        },
        next() {
            [pre, cur] = [cur, pre + cur];
            return { value: cur, done: false };
        },
    };
};

const iter = iterFibonacci();
for (let i = 0; i < 10; i++) {
    console.log(iter.next());
}

// 제너레이터
const genFibonacci = function* () {
    let [pre, cur] = [0, 1];
    while (true) {
        [pre, cur] = [cur, pre + cur];
        yield cur;
    }
};

const gen = genFibonacci();
for (let i = 0; i < 10; i++) {
    console.log(gen.next());
}
```

같은 무한 피보나치 수열을 구현하는데 있어서 제너레이터가 더 간단하다.

**비동기처리**

```jsx
const fetch = require('node-fetch');

const async = (generatorFunc) => {
    const generator = generatorFunc();

    const onResolved = (arg) => {
        const result = generator.next(arg);

        return result.done
            ? result.value
            : result.value.then((res) => onResolved(res));
    };
    return onResolved;
};

async(function* fetchToDo() {
    const url = 'https://jsonplaceholder.typicode.com/todos/1';
    const response = yield fetch(url);
    const todo = yield response.json();
    console.log(todo);
})(); // { userId: 1, id: 1, title: 'delectus aut autem', completed: false }
```

async/await 을 이용하면 더 간단하게 비동기처리가 가능하고 혹시 제너레이터 실행기가 필요하다면 co라이브러리를 사용한다.

### async / await

ES8에 도입된 async/await은 제너레이터보다 간단하고 가독성 좋게 비동기처리를 할 수 있고, 비동기처리를 동기처리 처럼 동작하도록 구현할 수 있게 해준다.

async/await 키워드는 프로미스를 기반으로 동작한다.

async 함수는 암묵적으로 반환값을 resolve하는 프로미스를 반환한다.

await 은 프로미스가 setteled 상태가 될 때까지 대기한다.

```jsx
const fetch = require('node-fetch');

async function fetchToDo() {
    const url = 'https://jsonplaceholder.typicode.com/todos/1';
    const response = await fetch(url);
    const todo = await response.json();
    console.log(todo);
}

fetchToDo(); // { userId: 1, id: 1, title: 'delectus aut autem', completed: false }
```

**에러처리**

에러는 호출자 방향으로 전파된다.

비동기처리를 위한 콜백패턴의 담점은 에러처리가 곤란하다는 것이다.

하지만 async/await 을 사용하면 명시적으로 호출할 수 있기 때문에 try ... catch 문을 이용해 에러를 캐치할 수 있다.

```jsx
const foo = async () => {
    try {
        const wrongUrl = 'https://wrong.url';
        const res = await fetch(wrongUrl);
        const data = await response.json();
        console.log(data);
    } catch (e) {
        console.error(e);
    }
};
foo();

// FetchError: request to https://wrong.url/ failed, reason: getaddrinfo ENOTFOUND wrong.url
//     at ClientRequest.<anonymous> (F:\WorkSpace\WorkSpace_Web\algorith.js\node_modules\node-fetch\lib\index.js:1461:11)
//     at ClientRequest.emit (events.js:315:20)
//     at TLSSocket.socketErrorListener (_http_client.js:426:9)
//     at TLSSocket.emit (events.js:315:20)
//     at emitErrorNT (internal/streams/destroy.js:92:8)
//     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
//     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
//   type: 'system',
//   errno: 'ENOTFOUND',
//   code: 'ENOTFOUND'
// }
```

하지만 async 함수 내에서 catch 문을 사용해서 에러처리를 하지 않으면 async함수는 발생한 에러를 reject 하는 프로미스를 반환한다.

```jsx
const fetch = require('node-fetch');

const foo = async () => {
    const wrongUrl = 'https://wrong.url';
    const res = await fetch(wrongUrl);
    const data = await res.json();
    return data;
};
foo().then(console.log).catch(console.error);
// FetchError: request to https://wrong.url/ failed, reason: getaddrinfo ENOTFOUND wrong.url
//     at ClientRequest.emit (events.js:315:20)
//     at TLSSocket.socketErrorListener (_http_client.js:426:9)
//     at TLSSocket.emit (events.js:315:20)
//     at emitErrorNT (internal/streams/destroy.js:92:8)
//     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
//     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
//   type: 'system',
//   errno: 'ENOTFOUND',
//   code: 'ENOTFOUND'
// }
```
